Development
Nikoniym/simpler-1 pull request #1
Opened 2018-05-16 17:18 UTC by Nikoniym

2018-05-16 23:39 UTC, psylone requested changes

2018-05-16 23:39 UTC, psylone commented on lib/middleware/logger.rb
> +    @app.call(env)
Воу-воу, зачем же нам 2 раза вызывать обработчик приложения. Мы уже вызвали выше, этого достаточно, здесь нужно просто вернуть rack-совместимый ответ.

2018-05-16 23:39 UTC, psylone commented on lib/simpler/controller.rb
> +      @request.env['simpler.params'] = @request.params.merge(@request.env['simpler.params'])
Лучше мерджить это в методе `params`, а результат закэшировать в инстанс-переменную.

2018-05-16 23:39 UTC, psylone commented on lib/simpler/controller.rb
> +      @request.env['simpler.params'] = @request.params.merge(@request.env['simpler.params'])
Также здесь проще было написать так: `@request.env['simpler.params'].merge!(@request.params)`.

2018-05-16 23:39 UTC, psylone commented on lib/simpler/view.rb
> +    def render(binding, content_type)
Так гораздо лучше, но ещё лучше будет если за рендеринг каждого типа ответа будет отвечать свой собственный класс.

2018-05-16 23:39 UTC, psylone commented on lib/simpler/router/route.rb
> +            return equal_element
Зачем ставить флаг если мы сразу же возвращаемся из метода?

2018-05-16 23:39 UTC, psylone commented on lib/simpler/router/route.rb
> +            equal_element = element_route_path == element_request_path if equal_element
`element_route_path == element_request_path` этого должно быть достаточно.

2018-05-16 23:39 UTC, psylone commented on lib/simpler/router/route.rb
> +            params[key] = element_request_path
Почему бы сразу не завести хэш в `env` и не пушить в него здесь? Тогда не понадобится метод `push_params`.

2018-05-16 23:39 UTC, psylone commented on lib/simpler/router/route.rb
> +        equal_element
С флагом явно перемудрил.

2018-05-17 00:49 UTC, Nikoniym commented on lib/middleware/logger.rb
> +    @app.call(env)
https://thinknetica.teachbase.ru/course_sessions/54367/take?material_id=211147#id=211131 на 25 минуте говориться именно так. Второй call вызывает само приложение.

2018-05-17 00:49 UTC, Nikoniym commented on lib/middleware/logger.rb
> +    @app.call(env)
Или я не прав? Без него пробовал, не работает, ошибки.

2018-05-17 00:49 UTC, Nikoniym commented on lib/simpler/view.rb
> +    def render(binding, content_type)
Тут я не понял про класс, можно объяснить по подробней.

2018-05-17 09:46 UTC, Nikoniym commented on lib/simpler/view.rb
> +    def render(binding, content_type)
И можно получить доступ к следующему уроку, просто я чувствую что могу не успеть? Это так?
Это задание доделаю как будет нужно, полностью. Просто весь день ждать проверки из - за двух трех строчек, чего - то не хочется. Лучше потратить его с пользой, изучая новый материал.

2018-05-18 10:39 UTC, psylone approved these changes

2018-05-18 10:39 UTC, psylone commented on lib/simpler/router/route.rb
> +        env['simpler.params'] = {}
Более понятно будет здесь сформировать хэш роут-параметров, а присвоить в `env` его выше где производится поиск роута или даже ещё выше где вызывается `route_for`.

2018-05-18 10:39 UTC, psylone commented on lib/simpler/view.rb
> +        TextRender
Теперь по фэн-шую )

2018-05-18 10:39 UTC, psylone commented on lib/simpler/controller.rb
> +        change_header
У нас могут быть и другие типы ответов поэтому будет лучше сделать установку заголовка более явным.

2018-05-19 12:05 UTC, merged